server:
  port: 56020

provider:
  address: 127.0.0.1:56010

spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 188.131.246.195:8848
        service: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}

dubbo:
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口
    port: 20882
  registry:
    address: nacos://188.131.246.195:8848
  application:
    qos-enable: false #dubbo运维服务是否开启
  consumer:
    check: false  #启动时就否检查依赖的服务