server:
 port: 56011

spring:
 application:
  name: nacos-restful-provider
 cloud:
  nacos:
   discovery:
    server-addr: localhost:8848
    service: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
   config:
    server-addr: localhost:8848
    file-extension: properties
