server:
 port: 56011

spring:
 application:
  name: nacos-restful-provider
 cloud:
  nacos:
   discovery:
    server-addr: 188.131.246.195:8848
    service: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
